#!/bin/bash
#Author: Ankit Sharma
#Date: 2-7-2019-
#Description: this script will setup openstack allinone 

#echo Please enter you Hostname

#read host

hostnamectl set-hostname controller

echo "192.168.0.10 controller" >> /etc/hosts

systemctl stop NetworkManager firewalld postfix
systemctl disable NetworkManager firewalld postfix
setenforce 0 
sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config

	
#echo " $ip $host" >> /etc/hosts

yum update -y 


if  [ $? -eq 0 ]
	then
	yum install centos-release-openstack-rocky -y
	echo 
	if [ $? -eq 0 ]
		then
		yum install openstack-packstack -y 
		echo 
		if [ $? -eq 0 ]
			then
			packstack --gen-answer-file /root/answer.txt
			packstack --answer-file /root/answer.txt
		
		fi
	fi

else
	echo "Openstack setup failed"
	exit 0

 

fi
